// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gembmfezizqcxxuzyueh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlbWJtZmV6aXpxY3h4dXp5dWVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MDc3MDcsImV4cCI6MjA2NDE4MzcwN30.xTfkdx9hMPAHt8E6XIolh4qFsyUkG77o29uHkPuEuy0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);